scrape_configs:
  - job_name: 'app-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8080']
  - job_name: 'mysql-metrics'
    static_configs:
      - targets: ['mysql-exporter:9104']